import { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'sr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'explore.all': 'Explore all',
    'stays': 'stays',
    'stay': 'stay',
    'search.results': 'Search Results for',
    'properties': 'Properties',
    'no.properties': 'No properties found',
    'try.adjusting': 'Try adjusting your search criteria',
    'find.adventure': 'Find your next adventure',
    'discover.places': 'Discover unique places to stay across the Balkans',
    'become.host': 'Become a Host',
    'my.bookings': 'My Bookings',
    'saved.properties': 'Saved Properties',
    'host.dashboard': 'Host Dashboard',
    'settings': 'Settings',
    'log.out': 'Log out',
    'account': 'Account',
    'night': 'night',
    'anywhere': 'Anywhere',
    'any.week': 'Any week',
    'add.guests': 'Add guests',
    'search': 'Search',
    'search.destinations': 'Search destinations...',
    // Categories
    'all': 'All',
    'mansions': 'Mansions',
    'cabins': 'Cabins',
    'beach': 'Beach',
    'mountains': 'Mountains',
    'city': 'City',
    'lofts': 'Lofts',
    'countryside': 'Countryside',
    'camping': 'Camping',
    // Filters
    'filters': 'Filters',
    'reset': 'Reset',
    'sort.by': 'Sort by',
    'most.popular': 'Most Popular',
    'highest.rated': 'Highest Rated',
    'price.low.high': 'Price: Low to High',
    'price.high.low': 'Price: High to Low',
    'price.per.night': 'Price per night',
    'bedrooms': 'Bedrooms',
    'beds': 'Beds',
    'bathrooms': 'Bathrooms',
    'guests': 'Guests',
    'amenities': 'Amenities',
    'any': 'Any',
    'guest': 'guest',
    'guests.plural': 'guests',
    // Property Detail
    'back': 'Back',
    'reviews': 'reviews',
    'hosted.by': 'Hosted by',
    'superhost': 'Superhost',
    'responds': 'Responds',
    'response.rate': 'response rate',
    'what.place.offers': 'What this place offers',
    'check.in.out': 'Check-in & Check-out',
    'check.in': 'Check-in',
    'check.out': 'Check-out',
    'check.in.date': 'Check-in date',
    'check.out.date': 'Check-out date',
    'add.dates': 'Add dates',
    'reserve': 'Reserve',
    'reserving': 'Reserving...',
    'reservation.successful': 'Reservation successful!',
    'check.email': 'Check your email for confirmation.',
    'total': 'Total',
    'cleaning.fee': 'Cleaning fee',
    'service.fee': 'Service fee',
    'copy.link': 'Copy link',
    'share.facebook': 'Share on Facebook',
    'share.twitter': 'Share on Twitter',
    'show.all.photos': 'Show all photos',
    'image.unavailable': 'Image unavailable',
    'property.not.found': 'Property not found',
    'property.not.exist': "The property you're looking for doesn't exist.",
    'go.home': 'Go Home',
    'something.wrong': 'Something went wrong',
    'try.again': 'Please try again later.',
    'back.to.home': 'Back to Home',
    // Privacy Policy
    'privacy.policy.title': 'Privacy Policy',
    'last.updated': 'Last updated: January 2025',
    // Terms of Service
    'terms.of.service.title': 'Terms of Service',
    // Booking Calendar
    'adult': 'adult',
    'adults': 'adults',
    'child': 'child',
    'children': 'children',
    'approximate.prices': 'Approximate prices in BAM for a 1-night stay',
    'base': 'Base',
    'nights': 'nights',
    'months.ago': 'months ago',
    // Footer
    'support': 'Support',
    'help.center': 'Help Center',
    'safety.information': 'Safety Information',
    'cancellation.options': 'Cancellation Options',
    'contact.us': 'Contact Us',
    'hosting': 'Hosting',
    'host.resources': 'Host Resources',
    'community.forum': 'Community Forum',
    'hosting.responsibly': 'Hosting Responsibly',
    'how.it.works': 'How it works',
    'newsroom': 'Newsroom',
    'careers': 'Careers',
    'investors': 'Investors',
    'legal': 'Legal',
    'privacy.policy': 'Privacy Policy',
    'terms.of.service': 'Terms of Service',
    'all.rights.reserved': 'All rights reserved',
    // Help Center
    'help.center.title': 'Help Center',
    'find.answers': 'Find answers to common questions',
    'search.for.help': 'Search for help...',
    'frequently.asked': 'Frequently Asked Questions',
    'no.results': 'No results found. Try a different search term.',
    'still.need.help': 'Still need help?',
    'support.available': 'Our support team is available 24/7 to assist you.',
    'contact.support': 'Contact Support',
    // Contact
    'contact.us.title': 'Contact Us',
    'here.to.help': "We're here to help! Get in touch with our team.",
    'email': 'Email',
    'phone': 'Phone',
    'office': 'Office',
    'support.hours': 'Support Hours',
    'send.message': 'Send us a Message',
    'name': 'Name',
    'subject': 'Subject',
    'message': 'Message',
    'send': 'Send Message',
    'message.sent': 'Message sent successfully!',
    'get.back': "We'll get back to you within 24 hours.",
    // Become Host
    'become.host.title': 'Become a Nexora Host',
    'share.space': 'Share your space and earn extra income while helping travelers discover authentic Balkan experiences',
    'list.space': 'List Your Space',
    'list.space.desc': 'Whether you have a spare room, entire apartment, or unique property, you can list it on Nexora. Our platform makes it easy to showcase your space to travelers.',
    'set.price': 'Set Your Price',
    'set.price.desc': 'You control your pricing and availability. Our dynamic pricing tools help you maximize your earnings while staying competitive in the market.',
    'welcome.guests': 'Welcome Guests',
    'welcome.guests.desc': 'Connect with travelers from around the world. Share local insights and create memorable experiences that showcase the best of Balkan hospitality.',
    'protected.supported': 'Protected & Supported',
    'protected.supported.desc': 'Our host protection program covers your property, and our support team is available 24/7 to help you succeed as a host.',
    'ready.start': 'Ready to Get Started?',
    'ready.start.desc': 'Join thousands of hosts across the Balkans who are earning extra income and sharing their spaces with travelers.',
    'browse.properties': 'Browse Properties',
    // How It Works
    'how.works.title': 'How Nexora Works',
    'discover.steps': 'Discover amazing stays across the Balkans in three simple steps',
    'search.step': '1. Search',
    'search.step.desc': 'Browse through our curated collection of authentic Balkan properties. Use filters to find the perfect location, price range, and amenities that match your travel style.',
    'book.step': '2. Book',
    'book.step.desc': 'Select your dates and number of guests. Our dynamic pricing ensures you get the best rate. Complete your reservation securely with instant confirmation.',
    'stay.step': '3. Stay',
    'stay.step.desc': 'Enjoy your authentic Balkan experience! Our hosts are committed to providing you with local insights and ensuring your stay is memorable.',
    'review.step': '4. Review',
    'review.step.desc': 'Share your experience and help future travelers discover the best Balkan stays. Your feedback helps us maintain high standards.',
    'start.search': 'Start Your Search',
    'language.english': 'English',
    'language.serbian': 'Srpski',
    // Become Host
    'list.space': 'List Your Space',
    'set.price': 'Set Your Price',
    'welcome.guests': 'Welcome Guests',
    'protected.supported': 'Protected & Supported',
    'ready.start': 'Ready to Get Started?',
    'browse.properties': 'Browse Properties',
    // FAQ
    'faq.cancel': 'How do I cancel my reservation?',
    'faq.cancel.answer': "You can cancel your reservation from your account dashboard. Cancellation policies vary by property and are clearly displayed before booking. Most properties offer free cancellation up to 48 hours before check-in.",
    'faq.payment': 'What payment methods do you accept?',
    'faq.payment.answer': 'We accept all major credit cards (Visa, Mastercard, American Express) and debit cards. Payment is processed securely at the time of booking.',
    'faq.contact.host': 'How do I contact my host?',
    'faq.contact.host.answer': "Once your booking is confirmed, you'll receive contact information for your host. You can also message them directly through the Nexora platform.",
    'faq.problem': 'What if I have a problem during my stay?',
    'faq.problem.answer': "Contact your host immediately through the platform. If the issue isn't resolved, reach out to our 24/7 support team. We're here to help ensure your stay is comfortable.",
    'faq.pets': 'Are pets allowed?',
    'faq.pets.answer': 'Pet policies vary by property. Check the property listing for specific pet policies, or contact the host directly to discuss your needs.',
    'faq.refund': 'What is your refund policy?',
    'faq.refund.answer': 'Refund policies depend on the cancellation policy of your specific booking. Check your booking confirmation for details, or contact support for assistance.',
    // Privacy Policy Details
    'privacy.matters': 'Your Privacy Matters',
    'privacy.intro': 'At Nexora, we are committed to protecting your privacy and ensuring the security of your personal information. This Privacy Policy explains how we collect, use, and safeguard your data when you use our platform.',
    'info.collect': 'Information We Collect',
    'info.collect.intro': 'We collect information that you provide directly to us, including:',
    'info.collect.account': 'Account information (name, email, phone number)',
    'info.collect.payment': 'Payment information (processed securely through third-party providers)',
    'info.collect.booking': 'Booking details and travel preferences',
    'info.collect.communications': 'Communications with hosts and our support team',
    'how.use': 'How We Use Your Information',
    'how.use.intro': 'We use your information to:',
    'how.use.process': 'Process and manage your bookings',
    'how.use.communicate': 'Communicate with you about your reservations',
    'how.use.improve': 'Improve our services and user experience',
    'how.use.offers': 'Send you relevant travel offers (with your consent)',
    'how.use.security': 'Ensure platform security and prevent fraud',
    'data.security': 'Data Security',
    'data.security.desc': 'We implement industry-standard security measures to protect your personal information. All data is encrypted in transit and at rest. We never share your information with third parties except as necessary to provide our services or as required by law.',
    'your.rights': 'Your Rights',
    'your.rights.intro': 'You have the right to:',
    'rights.access': 'Access your personal data',
    'rights.correct': 'Correct inaccurate information',
    'rights.delete': 'Request deletion of your data',
    'rights.optout': 'Opt-out of marketing communications',
    'rights.portability': 'Data portability',
    'privacy.contact': 'Contact Us',
    'privacy.contact.desc': 'If you have questions about this Privacy Policy or wish to exercise your rights, please contact us at',
    // Terms of Service Details
    'terms.agreement': 'Agreement to Terms',
    'terms.agreement.desc': 'By accessing and using Nexora, you agree to be bound by these Terms of Service. If you do not agree with any part of these terms, you may not use our platform.',
    'terms.user.responsibilities': 'User Responsibilities',
    'terms.user.intro': 'As a user of Nexora, you agree to:',
    'user.accurate': 'Provide accurate and complete information',
    'user.lawful': 'Use the platform only for lawful purposes',
    'user.respect': 'Respect the property and rights of hosts',
    'user.comply': 'Comply with all applicable laws and regulations',
    'user.security': 'Maintain the security of your account',
    'terms.booking': 'Booking Terms',
    'terms.booking.intro': 'When making a booking:',
    'booking.contract': 'You are entering into a contract directly with the host',
    'booking.payment': 'Payment is processed at the time of booking',
    'booking.cancellation': 'Cancellation policies vary by property and are clearly displayed',
    'booking.damages': 'You are responsible for any damages to the property',
    'booking.refunds': 'Refunds are subject to the host\'s cancellation policy',
    'terms.host.responsibilities': 'Host Responsibilities',
    'terms.host.intro': 'Hosts agree to:',
    'host.accurate': 'Provide accurate property descriptions and photos',
    'host.maintain': 'Maintain properties in safe and habitable condition',
    'host.honor': 'Honor confirmed reservations',
    'host.respond': 'Respond promptly to guest inquiries',
    'host.comply': 'Comply with all local laws and regulations',
    'terms.liability': 'Limitation of Liability',
    'terms.liability.desc': 'Nexora acts as a platform connecting guests and hosts. We are not responsible for the condition of properties, the conduct of hosts or guests, or any disputes that may arise. Our liability is limited to the service fees we collect.',
    'terms.modifications': 'Modifications',
    'terms.modifications.desc': 'We reserve the right to modify these terms at any time. Continued use of the platform after changes constitutes acceptance of the new terms.',
  },
  sr: {
    'explore.all': 'Istraži sve',
    'stays': 'smještaja',
    'stay': 'smještaj',
    'search.results': 'Rezultati pretrage za',
    'properties': 'Nekretnine',
    'no.properties': 'Nekretnine nisu pronađene',
    'try.adjusting': 'Pokušajte da prilagodite kriterijume pretrage',
    'find.adventure': 'Pronađite svoju sledeću avanturu',
    'discover.places': 'Otkrijte jedinstvena mesta za boravak širom Balkana',
    'become.host': 'Postanite domaćin',
    'my.bookings': 'Moje rezervacije',
    'saved.properties': 'Sačuvane nekretnine',
    'host.dashboard': 'Kontrolna tabla domaćina',
    'settings': 'Podešavanja',
    'log.out': 'Odjavi se',
    'account': 'Nalog',
    'night': 'noć',
    'anywhere': 'Bilo gde',
    'any.week': 'Bilo koja nedelja',
    'add.guests': 'Dodaj goste',
    'search': 'Pretraži',
    'search.destinations': 'Pretraži destinacije...',
    // Categories
    'all': 'Sve',
    'mansions': 'Vile',
    'cabins': 'Kolibe',
    'beach': 'Plaža',
    'mountains': 'Planine',
    'city': 'Grad',
    'lofts': 'Loftovi',
    'countryside': 'Selo',
    'camping': 'Kamping',
    // Filters
    'filters': 'Filteri',
    'reset': 'Resetuj',
    'sort.by': 'Sortiraj po',
    'most.popular': 'Najpopularnije',
    'highest.rated': 'Najbolje ocenjeno',
    'price.low.high': 'Cena: Od najniže',
    'price.high.low': 'Cena: Od najviše',
    'price.per.night': 'Cena po noći',
    'bedrooms': 'Spavaće sobe',
    'beds': 'Kreveti',
    'bathrooms': 'Kupatila',
    'guests': 'Gosti',
    'amenities': 'Sadržaji',
    'any': 'Bilo koje',
    'guest': 'gost',
    'guests.plural': 'gostiju',
    // Property Detail
    'back': 'Nazad',
    'reviews': 'recenzija',
    'hosted.by': 'Domaćin',
    'superhost': 'Superdomaćin',
    'responds': 'Odgovara',
    'response.rate': 'stopa odgovora',
    'what.place.offers': 'Šta ovo mesto nudi',
    'check.in.out': 'Prijava i odjava',
    'check.in': 'Prijava',
    'check.out': 'Odjava',
    'check.in.date': 'Datum prijave',
    'check.out.date': 'Datum odjave',
    'add.dates': 'Dodaj datume',
    'reserve': 'Rezerviši',
    'reserving': 'Rezervisanje...',
    'reservation.successful': 'Rezervacija uspešna!',
    'check.email': 'Proverite email za potvrdu.',
    'total': 'Ukupno',
    'cleaning.fee': 'Trošak čišćenja',
    'service.fee': 'Trošak usluge',
    'copy.link': 'Kopiraj link',
    'share.facebook': 'Podeli na Facebooku',
    'share.twitter': 'Podeli na Twitteru',
    'show.all.photos': 'Prikaži sve fotografije',
    'image.unavailable': 'Slika nije dostupna',
    'property.not.found': 'Nekretnina nije pronađena',
    'property.not.exist': 'Nekretnina koju tražite ne postoji.',
    'go.home': 'Idi na početnu',
    'something.wrong': 'Nešto je pošlo po zlu',
    'try.again': 'Molimo pokušajte ponovo kasnije.',
    'back.to.home': 'Nazad na početnu',
    // Privacy Policy
    'privacy.policy.title': 'Politika privatnosti',
    'last.updated': 'Poslednje ažuriranje: Januar 2025',
    // Terms of Service
    'terms.of.service.title': 'Uslovi korišćenja',
    // Booking Calendar
    'adult': 'odrasla osoba',
    'adults': 'odraslih osoba',
    'child': 'dete',
    'children': 'dece',
    'approximate.prices': 'Približne cene u BAM za boravak od 1 noć',
    'base': 'Osnovna',
    'nights': 'noći',
    'months.ago': 'meseca',
    // Footer
    'support': 'Podrška',
    'help.center': 'Centar za pomoć',
    'safety.information': 'Informacije o bezbednosti',
    'cancellation.options': 'Opcije otkazivanja',
    'contact.us': 'Kontaktirajte nas',
    'hosting': 'Domaćinstvo',
    'host.resources': 'Resursi za domaćine',
    'community.forum': 'Forum zajednice',
    'hosting.responsibly': 'Odgovorno domaćinstvo',
    'how.it.works': 'Kako funkcioniše',
    'newsroom': 'Vesti',
    'careers': 'Karijere',
    'investors': 'Investitori',
    'legal': 'Pravno',
    'privacy.policy': 'Politika privatnosti',
    'terms.of.service': 'Uslovi korišćenja',
    'all.rights.reserved': 'Sva prava zadržana',
    // Help Center
    'help.center.title': 'Centar za pomoć',
    'find.answers': 'Pronađite odgovore na česta pitanja',
    'search.for.help': 'Pretraži pomoć...',
    'frequently.asked': 'Često postavljana pitanja',
    'no.results': 'Nema rezultata. Pokušajte sa drugim pojmom.',
    'still.need.help': 'Još uvek trebate pomoć?',
    'support.available': 'Naš tim za podršku je dostupan 24/7 da vam pomogne.',
    'contact.support': 'Kontaktirajte podršku',
    // Contact
    'contact.us.title': 'Kontaktirajte nas',
    'here.to.help': 'Tu smo da pomognemo! Kontaktirajte naš tim.',
    'email': 'Email',
    'phone': 'Telefon',
    'office': 'Kancelarija',
    'support.hours': 'Radno vreme podrške',
    'send.message': 'Pošaljite nam poruku',
    'name': 'Ime',
    'subject': 'Predmet',
    'message': 'Poruka',
    'send': 'Pošalji poruku',
    'message.sent': 'Poruka je uspešno poslata!',
    'get.back': 'Odgovorićemo vam u roku od 24 sata.',
    // Become Host
    'become.host.title': 'Postanite domaćin',
    'share.space': 'Podelite svoj prostor i zaradite dodatni prihod',
    // How It Works
    'how.works.title': 'Kako Nexora funkcioniše',
    'discover.steps': 'Otkrijte neverovatne smještaje širom Balkana u tri jednostavna koraka',
    'search.step': '1. Pretraži',
    'search.step.desc': 'Pregledajte našu kuririsanu kolekciju autentičnih balkanskih nekretnina. Koristite filtere da pronađete savršenu lokaciju, cenovni rang i sadržaje koji odgovaraju vašem stilu putovanja.',
    'book.step': '2. Rezerviši',
    'book.step.desc': 'Izaberite datume i broj gostiju. Naše dinamičko određivanje cena osigurava da dobijete najbolju cenu. Završite rezervaciju sigurno sa trenutnom potvrdom.',
    'stay.step': '3. Ostani',
    'stay.step.desc': 'Uživajte u svom autentičnom balkanskom iskustvu! Naši domaćini su posvećeni pružanju lokalnih uvida i osiguravanju da vaš boravak bude nezaboravan.',
    'review.step': '4. Oceni',
    'review.step.desc': 'Podelite svoje iskustvo i pomozite budućim putnicima da otkriju najbolje balkanske smještaje. Vaše povratne informacije pomažu nam da održimo visoke standarde.',
    'start.search': 'Započni pretragu',
    'language.english': 'English',
    'language.serbian': 'Srpski',
    // Become Host
    'list.space': 'Objavi svoj prostor',
    'set.price': 'Postavi cenu',
    'welcome.guests': 'Dobrodošli gosti',
    'protected.supported': 'Zaštićeno i podržano',
    'ready.start': 'Spremni da počnete?',
    'browse.properties': 'Pregledaj nekretnine',
    // FAQ
    'faq.cancel': 'Kako mogu da otkažem rezervaciju?',
    'faq.cancel.answer': 'Možete otkazati rezervaciju sa kontrolne table vašeg naloga. Politika otkazivanja varira po nekretnini i jasno je prikazana pre rezervacije. Većina nekretnina nudi besplatno otkazivanje do 48 sati pre prijave.',
    'faq.payment': 'Koje načine plaćanja prihvatate?',
    'faq.payment.answer': 'Prihvatamo sve glavne kreditne kartice (Visa, Mastercard, American Express) i debitne kartice. Plaćanje se obrađuje sigurno u trenutku rezervacije.',
    'faq.contact.host': 'Kako mogu da kontaktiran domaćina?',
    'faq.contact.host.answer': 'Nakon što je vaša rezervacija potvrđena, dobićete kontakt informacije za vašeg domaćina. Takođe možete da im pišete direktno preko Nexora platforme.',
    'faq.problem': 'Šta ako imam problem tokom boravka?',
    'faq.problem.answer': 'Kontaktirajte svog domaćina odmah preko platforme. Ako problem nije rešen, obratite se našem timu za podršku 24/7. Tu smo da pomognemo da vaš boravak bude udoban.',
    'faq.pets': 'Da li su kućni ljubimci dozvoljeni?',
    'faq.pets.answer': 'Politika za kućne ljubimce varira po nekretnini. Proverite oglas nekretnine za specifične politike za kućne ljubimce, ili kontaktirajte domaćina direktno da razgovarate o vašim potrebama.',
    'faq.refund': 'Koja je vaša politika povraćaja novca?',
    'faq.refund.answer': 'Politika povraćaja novca zavisi od politike otkazivanja vaše specifične rezervacije. Proverite potvrdu rezervacije za detalje, ili kontaktirajte podršku za pomoć.',
    // Privacy Policy Details
    'privacy.matters': 'Vaša privatnost je važna',
    'privacy.intro': 'U Nexora, posvećeni smo zaštiti vaše privatnosti i osiguravanju bezbednosti vaših ličnih podataka. Ova Politika privatnosti objašnjava kako prikupljamo, koristimo i štitimo vaše podatke kada koristite našu platformu.',
    'info.collect': 'Informacije koje prikupljamo',
    'info.collect.intro': 'Prikupljamo informacije koje nam direktno pružate, uključujući:',
    'info.collect.account': 'Informacije o nalogu (ime, email, broj telefona)',
    'info.collect.payment': 'Informacije o plaćanju (obrađuju se sigurno preko trećih strana)',
    'info.collect.booking': 'Detalji rezervacije i preferencije putovanja',
    'info.collect.communications': 'Komunikacije sa domaćinima i našim timom za podršku',
    'how.use': 'Kako koristimo vaše informacije',
    'how.use.intro': 'Koristimo vaše informacije za:',
    'how.use.process': 'Obradu i upravljanje vašim rezervacijama',
    'how.use.communicate': 'Komunikaciju sa vama o vašim rezervacijama',
    'how.use.improve': 'Poboljšanje naših usluga i korisničkog iskustva',
    'how.use.offers': 'Slanje relevantnih ponuda za putovanja (uz vašu saglasnost)',
    'how.use.security': 'Osiguravanje bezbednosti platforme i sprečavanje prevara',
    'data.security': 'Bezbednost podataka',
    'data.security.desc': 'Primenjujemo standardne mere bezbednosti industrije za zaštitu vaših ličnih podataka. Svi podaci su šifrovani u tranzitu i u mirovanju. Nikada ne delimo vaše informacije sa trećim stranama osim što je neophodno za pružanje naših usluga ili kako zahteva zakon.',
    'your.rights': 'Vaša prava',
    'your.rights.intro': 'Imate pravo da:',
    'rights.access': 'Pristupite svojim ličnim podacima',
    'rights.correct': 'Ispravite netačne informacije',
    'rights.delete': 'Zatražite brisanje vaših podataka',
    'rights.optout': 'Odustanete od marketinških komunikacija',
    'rights.portability': 'Prenos podataka',
    'privacy.contact': 'Kontaktirajte nas',
    'privacy.contact.desc': 'Ako imate pitanja o ovoj Politici privatnosti ili želite da iskoristite svoja prava, molimo kontaktirajte nas na',
    // Terms of Service Details
    'terms.agreement': 'Saglasnost sa uslovima',
    'terms.agreement.desc': 'Pristupanjem i korišćenjem Nexora, slažete se da ste vezani ovim Uslovima korišćenja. Ako se ne slažete sa bilo kojim delom ovih uslova, ne smete koristiti našu platformu.',
    'terms.user.responsibilities': 'Odgovornosti korisnika',
    'terms.user.intro': 'Kao korisnik Nexora, slažete se da:',
    'user.accurate': 'Pružate tačne i potpune informacije',
    'user.lawful': 'Koristite platformu samo u zakonite svrhe',
    'user.respect': 'Poštujete imovinu i prava domaćina',
    'user.comply': 'Pridržavate se svih primenjivih zakona i propisa',
    'user.security': 'Održavate bezbednost svog naloga',
    'terms.booking': 'Uslovi rezervacije',
    'terms.booking.intro': 'Prilikom rezervacije:',
    'booking.contract': 'Ulazite u ugovor direktno sa domaćinom',
    'booking.payment': 'Plaćanje se obrađuje u trenutku rezervacije',
    'booking.cancellation': 'Politika otkazivanja varira po nekretnini i jasno je prikazana',
    'booking.damages': 'Odgovorni ste za bilo kakvu štetu na nekretnini',
    'booking.refunds': 'Povraćaj novca zavisi od politike otkazivanja domaćina',
    'terms.host.responsibilities': 'Odgovornosti domaćina',
    'terms.host.intro': 'Domaćini se slažu da:',
    'host.accurate': 'Pružaju tačne opise nekretnina i fotografije',
    'host.maintain': 'Održavaju nekretnine u bezbednom i pogodnom stanju',
    'host.honor': 'Poštuju potvrđene rezervacije',
    'host.respond': 'Brzo odgovaraju na upite gostiju',
    'host.comply': 'Pridržavaju se svih lokalnih zakona i propisa',
    'terms.liability': 'Ograničenje odgovornosti',
    'terms.liability.desc': 'Nexora deluje kao platforma koja povezuje goste i domaćine. Nismo odgovorni za stanje nekretnina, ponašanje domaćina ili gostiju, ili bilo kakve sporove koji mogu nastati. Naša odgovornost je ograničena na naknade za usluge koje prikupljamo.',
    'terms.modifications': 'Izmene',
    'terms.modifications.desc': 'Zadržavamo pravo da ove uslove izmenimo u bilo kom trenutku. Nastavak korišćenja platforme nakon izmena predstavlja prihvatanje novih uslova.',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'en';
  });

  // Sync with other tabs
  useEffect(() => {
    const handleStorageChange = (e: StorageEvent) => {
      if (e.key === 'language' && e.newValue) {
        setLanguageState(e.newValue as Language);
      }
    };

    window.addEventListener('storage', handleStorageChange);
    return () => window.removeEventListener('storage', handleStorageChange);
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

// eslint-disable-next-line react-refresh/only-export-components
export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

